name: Release website
on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          npm i -g yarn
          yarn
          yarn workspace dbgate-web build
          find . -name "node_modules" -exec rm -rf '{}' +
          rsync -vrm   ./* ${{ secrets.USER_IP }}:/var/www/dbgate/
          ssh ${{ secrets.USER_IP }} "nvm use 16 && cd /var/www/dbgate/ && yarn && kill -9 $(sudo lsof -i tcp:7000 -t) && kill -9 $(sudo lsof -i tcp:7001 -t) && yarn start:prod"